#
# Copyright 2000-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# See file CREDITS for list of people who contributed to this
# project.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307 USA
#

obj-${CONFIG_MOXA_CONSOLE} += moxa_console.o 
obj-${CONFIG_MOXA_LIB} += moxa_lib.o
obj-y += wdt_diag.o ds1374_wdt.o
obj-y += sys_info.o
obj-${CONFIG_MOXA_USB_SIGNAL_INIT} += usb_signal_init.o
obj-${CONFIG_MOXA_BOOT} += moxa_boot.o
obj-${CONFIG_MOXA_UPGRADE} += moxa_upgrade.o

